### ISSUE TITLE
Ascension crashing when starts

### ISSUE THREAD

**Issue by Hefesto0** [5and5/BO1-StratTester#33]
I play ascension on my base game but every time when I start ascension on strat tester, my game crashes 

![image-12](https://github.com/5and5/BO1-StratTester/assets/124174688/f3f8a75e-4c6c-47fb-9528-b50dfd4ca524)

Thanks

**Comment by llPh3NiXll** [comment]
I would say try to re-install the mod completly. These kind of errors usually are due to files missing.

**Comment by TTS4life** [comment]
I would also recommend trying to re-install game_mod and Strat Tester. This issue is not something thats a result of Strat Tester, but something with installs.

If that doesn't fix it, does this happen only when using Strat Tester? Or does it also do this when you launch Ascension with no mod currently loaded (meaning you launched `BO_Mods.bat`, but did not load a mod yet or clicked `UNMODDED BLACK OPS` in the mods option on the TV). Is it exclusive to one map or multiple? Do you own the game/DLC legitimately through Steam? Are you trying to use Pluto (not recommended) or vanilla Black Ops?

**Comment by Hefesto0** [comment]
I don't try re-install yet but my game is the vanilla BO1 and I have DLC legitimately through. Now I'm going to the college, later I will try re-install and back with more informations.
Until moment, thanks

**Comment by Hefesto0** [comment]
I re-made my iw_42 and fixed it, idk which camo did it but dont matter, working now
