### ISSUE TITLE
23 Zombies on Moon

### ISSUE THREAD

**Issue by llPh3NiXll** [5and5/BO1-StratTester#37]
Hello,

On Moon when testing with 23 zombies instead of 24, when you shoot the Wavegun (which is supposed to prevent zombies from respawning until they explode), there is an extra zombie which is able to respawn instantly, this isn't supposed to happen.

I would say either you would want to fix that or make the setting to make the astronaut to spawn an instant thing.

Thanks.

**Comment by TTS4life** [comment]
Can you provide a sample video of this happening? I did a test just now and I don't see this issue happening. I set the horde count to 20 and did not see 4 zombies spawning in particularly faster than the rest, but that could be a testing limitation on my end. I provided a video of my side of testing.

https://github.com/5and5/BO1-StratTester/assets/60669844/0e85cc31-a0fc-43e8-8bca-ba5ac317429e

As far as I know, the logic for _when_ to spawn a zombie has not been altered. Only the calculations for determining the spawn rate to not be a recursive function

**Comment by llPh3NiXll** [comment]
It seems like this works only with 23 zombies instead of 24.

**Comment by Zi0MIX** [comment]
Ok so the issue was that the function controlling horde count was missing one call to internal engine function. 
But i want to clear a misconception, if not for that bug that's causing zombies to not spawn for few seconds after you kill the entire horde, they'd spawn as soon as you shoot, exploding zombies no longer take space in your horde count.

For testing this stuff i recommend `/cg_drawFPS simple ; ai_showCount 1`
